### ISSUE TITLE
pbdsHeaderShadow directive not working

### ISSUE THREAD

**Issue by denishpb** [PBGUX/bower-designsystem#10]
Hi, 
pbdsHeaderShadow is not working as the directive is throwing an error. The error is related to angular jqlite object trying to access jquery scrollTop function. please fix the same. Converting jqlite object to jquery object inside the directive solves the problem.
Let me know if I am doing anything wrong.
Thanks.

**Comment by smlombardi** [comment]
Where are you seeing this error?  Which Browser (version) and OS (version)?

**Comment by denishpb** [comment]
Chrome Latest on Windows 7

In minified pb.ds.components.js, Converting jqlite object to jquery in worked.

**Comment by smlombardi** [comment]
We will look into it.  We haven't seen this before in our testing.

**Comment by denishpb** [comment]
If we use browsersync for development server and keep the jquery before angularjs, it doesnt work. 
We have to put angularjs before jquery and because of that jqlite do not inherit jquery functions.
So in angular directives, it's better bet to use jquery objects than the angular jqlite objects to make full use of jquery functions

**Comment by danielcollettepb** [comment]
@denishpb this was great feedback, thank you!

We are trying to reduce jQuery dependency whenever possible. Rather than converting to a jQuery object I revised the directive, removing .scrollTop() and using the $window `pageYOffset` as follows:

```
angular.element($window).on('scroll', function () {
   if (this.pageYOffset > 20) {
      element.addClass('shadow');
   } else {
      element.removeClass('shadow');
   }
});
```

Also note that `.bind()` is deprecated so it is replaced with `.on()`.

Here is a screenshot of Mac and Windows 7 Chrome:

![image](https://cloud.githubusercontent.com/assets/6116867/20364859/bcb37528-ac12-11e6-979f-f562a432dc0a.png)

On a side note, as a best practice jQuery should be loaded before AngularJS.

This change will come in the 3.1 update targeted for mid-December.

**Comment by denishpb** [comment]
Thanks. I ll update my pb.ds.components.js accordingly.
